# Generated by Django 3.1.6 on 2021-04-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redditpost',
            name='author',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='created_utc',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='dislike',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='phash',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='post_id',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='selected',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='source_link',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='sub_name',
            field=models.CharField(blank=True, default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='title',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='url',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='wrong_format',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
