# Generated by Django 3.1.6 on 2021-04-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_auto_20210417_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redditpost',
            name='selected',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
