# Generated by Django 3.1.6 on 2021-04-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_auto_20210417_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='redditpost',
            name='mal_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
