# Generated by Django 3.1.6 on 2021-04-18 14:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_redditpost_mal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redditpost',
            name='invisible_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=9999), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='visible_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=9999), blank=True, null=True, size=None),
        ),
    ]
